### ISSUE TITLE
Could you please provide the CAMRa2011 datasets?

### ISSUE THREAD

**Issue by FizzerYu** [zenogantner/MyMediaLite#482]
Hi,
Thank you for providing a excellent recommendation tool.  We want to do some further experiments based on CAMRa2011 datasets, but it seems hard to find the origin dataset.
So could you please provide the CAMRa2011 datasets?

**Comment by zenogantner** [comment]
I do not have access to the data set any more. Your best chances may be the with the challenge organizers: https://recsys.acm.org/recsys11/camra/

Otherwise, it may be better to perform new research with publicly available data sets like the ones provided by GroupLens: https://grouplens.org/datasets/movielens/

**Comment by FizzerYu** [comment]
Well, the organizers don't provide this datasets anymore.
But thank you very much!
